"""update Transaction table to support transactions with same hash

Revision ID: 2d1dd9b77b17
Revises: 82917d899ff2
Create Date: 2025-07-08 12:02:44.027503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d1dd9b77b17'
down_revision: Union[str, Sequence[str], None] = '82917d899ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_transactions_hash'), ['hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_hash'))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
