"""add transactions table

Revision ID: 579968fa9466
Revises: 1b8fdebef5b9
Create Date: 2025-07-07 15:48:12.666968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579968fa9466'
down_revision: Union[str, Sequence[str], None] = '1b8fdebef5b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('from_address', sa.String(), nullable=True),
    sa.Column('to_address', sa.String(), nullable=True),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_address'], ['addresses.address'], ),
    sa.ForeignKeyConstraint(['to_address'], ['addresses.address'], ),
    sa.PrimaryKeyConstraint('hash', 'chain_id', 'token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
