"""improve balance table

Revision ID: 5ac206364877
Revises: 3a1c2b4e5f67
Create Date: 2025-07-09 18:16:13.607462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac206364877'
down_revision: Union[str, Sequence[str], None] = '3a1c2b4e5f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('balance', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.create_unique_constraint('unique_balance', ['address', 'chain_id', 'token'])
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('unique_balance', type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('balance')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
