"""add processed transactions table

Revision ID: 82917d899ff2
Revises: 579968fa9466
Create Date: 2025-07-08 10:35:23.050353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82917d899ff2'
down_revision: Union[str, Sequence[str], None] = '579968fa9466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_transactions',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('hash', 'chain_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_transactions')
    # ### end Alembic commands ###
